# Generated by Django 6.0.6 on 2026-06-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uwr_cheatsheets', '0002_note_lecture_from_note_lecture_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['lecture_from', 'title']},
        ),
    ]
