# Generated by Django 6.0.6 on 2026-06-28 22:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('term', models.CharField(choices=[('Z', 'zimowy'), ('L', 'letni')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='notes.course')),
            ],
            options={
                'unique_together': {('course', 'year_start', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lecture_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='notes_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('author', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.courserun')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lecture_from', 'title'],
                'permissions': [('can_publish_directly', 'Może publikować bez moderacji')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lecture_to__gte', models.F('lecture_from'))), name='lecture_to_gte_from')],
            },
        ),
    ]
