# Generated by Django 6.0.6 on 2026-06-28 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["lecture_from", "title"],
                "permissions": [
                    ("can_publish_directly", "Może publikować bez moderacji")
                ],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekująca"),
                    ("approved", "Zatwierdzona"),
                    ("rejected", "Odrzucona"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="pdf",
            field=models.FileField(
                upload_to="notes_pdfs/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
